/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cbiuser' at '7/28/16 11:07 AM' with Gradle 2.14
 *
 * @author cbiuser, @date 7/28/16 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
